### ISSUE TITLE
API changes break homebridge-platform-myq

### ISSUE THREAD

**Issue by coneslayer** [rainlake/homebridge-platform-myq#16]
As of today, starting Homebridge gives the following error:

```
[8/6/2019, 9:33:00 PM] [MyQ Platform] Initializing MyQ platform...
[8/6/2019, 9:33:00 PM] [MyQ Platform] MyQ Server error, returncode=[undefined], errormessage=[undefined]
[8/6/2019, 9:33:00 PM] Error: homebridge-platform-myq has intentially brought down HomeBridge - please fix your configuration!
    at MyQPlatform.<anonymous> (/usr/lib/node_modules/homebridge-platform-myq/index.js:309:15)
    at Request._callback (/usr/lib/node_modules/homebridge-platform-myq/index.js:58:28)
    at Request.self.callback (/usr/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
[8/6/2019, 9:33:00 PM] Got SIGTERM, shutting down Homebridge...
```

This appears to be due to substantial API changes at Chamberlain's servers. There is a discussion that may be helpful at:
https://github.com/arraylabs/pymyq/issues/22

**Comment by socalcal** [comment]
Looks to be broken again?

**Comment by Cardo1** [comment]
Yes, it looks like the login system in this plugin is now out of date.  Are the developers still active?  I appreciate there is now native support in the US/Canada, however unfortunately they don't seem to be in any rush to release a European version of the Home Bridge.

**Comment by Cardo1** [comment]
This plugin is actively maintained and I can confirm is currently working:
https://github.com/caseywebdev/homebridge-chamberlain

**Comment by socalcal** [comment]
that plugin doesn't support outlets through myq, though, right?
