### ISSUE TITLE
Fails to add accessory b/c of missing displayName

### ISSUE THREAD

**Issue by searls** [rainlake/homebridge-platform-myq#2]
I'm seeing this when I add this plugin to my config:

```
[MyQ Platform] Initializing platform accessory 'Garage Door Opener'...
[MyQ Platform] Initializing platform accessory ''...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:45
  if (!displayName) throw new Error("Accessories must be created with a non-empty displayName.");
                    ^

Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:45:27)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:375:21)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:343:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at MyQPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-myq/index.js:292:13)
    at Request._callback (/usr/local/lib/node_modules/homebridge-platform-myq/index.js:170:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-myq/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)

```

**Comment by rainlake** [comment]
Did you set a name in you Myq app?

**Comment by searls** [comment]
In which app? Their iOS app? No

**Comment by rainlake** [comment]
Yes. The iOS app. Please set a name in iOS app first. This plugin does not
support a device without name currently.

**Comment by searls** [comment]
Ok thanks!
